# Generated by Django 3.2.9 on 2021-12-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image'),
        ('profiles', '0010_alter_profile_image'),
    ]

    operations = [
    ]
