# Generated by Django 3.2.9 on 2021-12-31 16:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_0002_profile_image_0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profiles/user.png', upload_to='profiles'),
        ),
    ]
