# Generated by Django 3.2 on 2022-01-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220130_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='receiver',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
    ]
