# Generated by Django 3.2 on 2022-01-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220130_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.roomchat'),
        ),
    ]
