# Generated by Django 3.2 on 2022-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chat_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomchat',
            old_name='name',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='sender',
            field=models.CharField(default=1, max_length=1055),
            preserve_default=False,
        ),
    ]
