# Generated by Django 3.2 on 2022-01-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20220130_1320'),
        ('chat', '0010_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
