# Generated by Django 3.2 on 2022-01-31 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_roomchat_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='profile',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='receiver_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomchat',
            name='sender_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
    ]
