# Generated by Django 3.2 on 2022-02-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chat_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
