# Generated by Django 3.2 on 2022-02-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_chat_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='receiver_profile',
        ),
        migrations.RemoveField(
            model_name='roomchat',
            name='sender_profile',
        ),
    ]
