# Generated by Django 3.2 on 2022-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20220204_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected',
            name='room',
        ),
        migrations.AddField(
            model_name='connected',
            name='sender',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
