# Generated by Django 3.2 on 2022-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20220204_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected',
            name='sender',
        ),
        migrations.AddField(
            model_name='connected',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
