# Generated by Django 3.2 on 2022-02-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20220204_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected',
            name='room_id',
        ),
        migrations.AddField(
            model_name='connected',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connected', to='chat.roomchat'),
            preserve_default=False,
        ),
    ]
