# Generated by Django 3.2 on 2022-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20220205_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/message_photos'),
        ),
    ]
