# Generated by Django 3.2 on 2022-02-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20220210_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
