# Generated by Django 3.2.9 on 2021-12-09 05:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
