# Generated by Django 3.2.9 on 2021-12-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
