# Generated by Django 3.2.9 on 2021-12-23 15:48

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20211223_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
