# Generated by Django 3.2.9 on 2021-12-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
