# Generated by Django 3.1 on 2022-01-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='command',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
    ]
