# Generated by Django 3.1 on 2022-01-23 06:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_notification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/posts'),
        ),
    ]
