# Generated by Django 3.1 on 2022-01-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_messagemodel_threadmodel'),
        ('feed', '0024_auto_20220123_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.threadmodel'),
        ),
    ]
