# Generated by Django 3.2 on 2022-02-26 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0029_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
