# Generated by Django 3.2 on 2022-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
