# Generated by Django 3.2 on 2022-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20220130_1320'),
        ('feed', '0032_delete_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='profiles.Profile'),
        ),
    ]
