# Generated by Django 3.2 on 2022-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_auto_20220120_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
